# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-27 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_disabled_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='If Yes please indicate name(s)')),
                ('dependent_insurance_other_continue', models.CharField(blank=True, max_length=10, null=True, verbose_name='Do you or your dependents have other health coverage?')),
                ('policy_holders_name', models.CharField(max_length=50, verbose_name="Policy Holder's Name")),
                ('policy_number', models.CharField(max_length=50, verbose_name='Policy Number')),
                ('effective_date', models.DateField(verbose_name='Effective Policy Date')),
                ('coverage', models.CharField(default='ACCEPT', max_length=50, verbose_name='coverage')),
                ('decline_reasons', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reason for Decline')),
                ('others', models.CharField(blank=True, max_length=150, null=True, verbose_name='Others')),
                ('dependent_disabled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LookupModel', verbose_name='Are you or any dependent(s) disabled?')),
            ],
        ),
        migrations.CreateModel(
            name='DependentInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_height_feet', models.CharField(max_length=50, verbose_name='Self-Height (feet)')),
                ('self_height_inches', models.CharField(max_length=50, verbose_name='Self-Height (inches)')),
                ('self_weight_lbs', models.CharField(max_length=50, verbose_name='Self-Weight (Pounds)')),
                ('spouse_height_feet', models.CharField(max_length=50, verbose_name='Spouse-Height (feet)')),
                ('spouse_height_inches', models.CharField(max_length=50, verbose_name='Spouse-Height (inches)')),
                ('spouse_weight_lbs', models.CharField(max_length=50, verbose_name='Spouse-Weight (Pounds)')),
                ('anticipate_hozpital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_anticipate_hozpital', to='core.LookupModel', verbose_name='Are you or any of your dependent(s) anticipating hospitalization or surgery, or had surgery or hospitalization\nrecommended that has not been performed? * If Yes, please provide information below')),
                ('dependent_pregnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_dependent_pregnant', to='core.LookupModel', verbose_name='Are you or any dependent(s) currently pregnant or suspect you / they may be pregnant? * If Yes, please provide due date and detail in space provided below')),
                ('diagnose_treated', models.ManyToManyField(related_name='dep_diagnose_treated', to='core.LookupModel', verbose_name='Have you or any of your dependent(s) been diagnosed or treated for, or has hospitalization or surgery not yet performed been\n        recommended for, any of the following conditions in the past five (5) years? If so, the plan requires you to disclose these conditions solely\n        for underwriting purposes (and you can properly disclose by checking “Yes” for each of the conditions for which you and/or your\n        dependents have previously received diagnosis, treatment or a recommendation for hospitalization or surgery not yet performed).\n        Although neither you nor your dependents will be denied coverage because of any previous treatment, diagnosis or recommendation for\n        hospitalization or surgery not yet performed for any condition, if you fail to disclose any previous treatment, diagnosis, recommendation\n        of hospitalization or surgery not yet performed for a condition listed below, the health plan will not cover any medical expenses, diagnosis,\n        treatment, services, supplies, surgeries or hospitalizations for that undisclosed condition related or attributable, to the coverage sought\n        as part of this application. NOTE: You are required to disclose any updates to these health questions that may arise prior to the effective date of your coverage')),
                ('past_24_med_cond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_past_24_med_cond', to='core.LookupModel', verbose_name='Have you or any of your dependent(s) had any medical conditions in the past 24 months requiring medical care,\n        prescription management, surgery, or hospitalization? * If Yes, please provide information on who and for what conditions in space provided below')),
                ('past_24_mon_med_exp_5k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_past_24_mon_med_exp_5k', to='core.LookupModel', verbose_name='In the past 24 months, have you or any of your dependent(s) had more than $5,000 in medical expenses? * If Yes, please provide information on who and for what medical conditions in space provided below')),
                ('past_5_insu_decl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_past_5_ins_decl', to='core.LookupModel', verbose_name='Within the past 5 years, have you or any dependent ever had an application for insurance declined, postponed,\n        rated or otherwise modified?')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empl_full_name', models.CharField(max_length=250, verbose_name='Employee Full Name')),
                ('empl_hire_date', models.DateTimeField(verbose_name='Hire Date')),
                ('empl_dob', models.DateTimeField(verbose_name='DOB')),
                ('empl_ssn', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='address2')),
                ('city', models.CharField(max_length=150, verbose_name='city')),
                ('state', models.CharField(max_length=200, verbose_name='state')),
                ('zip_code', models.CharField(max_length=50, verbose_name='zip_code')),
                ('current_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='User in This Page')),
                ('all_forms_complete', models.BooleanField(verbose_name='All Forms Completed')),
                ('empl_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_gender_lookupmodel', to='core.LookupModel', verbose_name='Gender')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.Employer', verbose_name='Employer Info')),
                ('form_type', models.ManyToManyField(related_name='empl_form_type', to='core.LookupModel', verbose_name='Form Type')),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Logged In User')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='HealthQuestionnaireModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthquestionaire.EmployeeModel', verbose_name='Employee')),
            ],
            options={
                'db_table': 'health_questionnaire',
            },
        ),
        migrations.CreateModel(
            name='MedicalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member', models.CharField(max_length=250, verbose_name='Family Member')),
                ('disease_diag_treat', models.CharField(max_length=250, verbose_name='Disease/Diagnosis/Treatment')),
                ('date_of_onset', models.CharField(max_length=50, verbose_name='Date Of Onset (Month/Year)')),
                ('date_last_seen', models.CharField(max_length=50, verbose_name='Date Last Seen By Physician')),
                ('remaining_symp_probs', models.CharField(max_length=500, verbose_name='Remaining Symptoms Or Problems')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthquestionaire.EmployeeModel', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member', models.CharField(max_length=250, verbose_name='Family Member')),
                ('medication_rx_injection', models.CharField(max_length=250, verbose_name='Medication/Rx/Injection')),
                ('dosage', models.CharField(max_length=50, verbose_name='Dosage')),
                ('med_condition', models.CharField(max_length=350, verbose_name='Medical Condition')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthquestionaire.EmployeeModel', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='coveragemodel',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthquestionaire.EmployeeModel', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='coveragemodel',
            name='tobacco_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_tobacco_use', to='core.LookupModel', verbose_name='Tobacco Use'),
        ),
    ]
