# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('core', '0005_auto_20190715_1729'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empl_dependents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EmployeeDependent', verbose_name='Dependents')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Employer', verbose_name='Employer Info')),
            ],
        ),
        migrations.CreateModel(
            name='HealthQuestionnaireModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tobacco_use', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, null=True, verbose_name='Does tobacco use affect the rates?')),
                ('dependent_disabled', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, null=True, verbose_name='Are you or any dependent(s) disabled?')),
                ('dependent_disabled_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='If Yes please indicate name(s)')),
                ('dependent_insurance_other_continue', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, null=True, verbose_name='Do you or your dependents have other health coverage?')),
                ('policy_holders_name', models.CharField(max_length=50, verbose_name="Policy Holder's Name")),
                ('policy_number', models.CharField(max_length=50, verbose_name='Policy Number')),
                ('effective_date', models.DateTimeField(auto_now_add=True, verbose_name='Effective Policy Date')),
                ('coverage', models.CharField(choices=[('DECLINE', 'I Decline Coverage'), ('ACCEPT', 'I Accept Coverage')], default='ACCEPT', max_length=50, verbose_name='coverage')),
                ('decline_reasons', models.CharField(blank=True, choices=[('SP_EMP_PLAN', "SPOUSE'S EMPLOYER'S PLAN"), ('IND_PLAN', 'INDIVIDUAL PLAN'), ('MEDICARE', 'MEDICARE'), ('MEDICAID', 'MEDICAID'), ('COBRA_PREV_EMP', 'COBRA FROM PREVIOUS EMPLOYER'), ('VA_ELIG', 'VA ELIGIBILITY'), ('NO_COVERAGE_NOW', 'I HAVE NO COVERAGE AT THIS TIME'), ('OTHERS', 'OTHERS')], max_length=50, null=True, verbose_name='Reason for Decline')),
                ('others', models.CharField(blank=True, max_length=150, null=True, verbose_name='Others')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthquestionaire.EmployeeModel', verbose_name='Employee')),
                ('self_height_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_height_weight', to='core.HeightWeight', verbose_name='Self')),
                ('spouse_height_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouse_height_weight', to='core.HeightWeight', verbose_name='Spouse')),
            ],
            options={
                'db_table': 'health_questionnaire',
            },
        ),
    ]
