# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190727_0907'),
        ('healthquestionaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemodel',
            name='coverage_level',
            field=models.ManyToManyField(related_name='coverage_level', to='core.LookupModel', verbose_name='Coverage Level'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cell Phone'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='home_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Home Phone'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='hours_worked_per_week',
            field=models.IntegerField(default=40, verbose_name='Hours Worked Per Week (Required in Enrolling)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='marital_status',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='empl_marital_status', to='core.LookupModel', verbose_name='Marital status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='spouse_buisness_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Spouse's Buisness Phone"),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='spouse_employer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Spouse's Employer"),
        ),
        migrations.AlterField(
            model_name='coveragemodel',
            name='coverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_accept', to='core.LookupModel', verbose_name='Accept/Decline'),
        ),
        migrations.RemoveField(
            model_name='coveragemodel',
            name='decline_reasons',
        ),
        migrations.AddField(
            model_name='coveragemodel',
            name='decline_reasons',
            field=models.ManyToManyField(related_name='reasons_for_decline', to='core.LookupModel', verbose_name='Reason for Decline'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='all_forms_complete',
            field=models.BooleanField(default=False, verbose_name='All Forms Completed'),
        ),
    ]
