# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0002_auto_20190730_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='employer',
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='form_type',
            field=models.ManyToManyField(default=40, related_name='empl_form_type', to='core.LookupModel', verbose_name='Form Type'),
        ),
    ]
