# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0002_auto_20190727_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemodel',
            name='dependent_isu_coverage_carrier',
            field=models.CharField(default='', max_length=250, verbose_name='If Yes, name of Carrier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coveragemodel',
            name='dependent_insurance_other_continue',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='empl_other_insu_coverage', to='core.LookupModel', verbose_name='Do you, your spouse or your dependents have other health insurance coverage that will continue in addition to this coverage?'),
            preserve_default=False,
        ),
    ]
