# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-11 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0002_auto_20190811_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragemodel',
            name='coverage_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_level', to='core.LookupModel', verbose_name='* Coverage Level'),
        ),
        migrations.AlterField(
            model_name='coveragemodel',
            name='dependent_disabled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_dependent_disabled', to='core.LookupModel', verbose_name='* Are you or any dependent(s) disabled?'),
        ),
        migrations.AlterField(
            model_name='coveragemodel',
            name='dependent_insurance_other_continue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_depend_other_insu_coverage', to='core.LookupModel', verbose_name='* Do you or any of your family have other health insurance that will continue in addition to this coverage?'),
        ),
        migrations.AlterField(
            model_name='coveragemodel',
            name='tobacco_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tobacco_use', to='core.LookupModel', verbose_name='* Tobacco Use'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='city',
            field=models.CharField(max_length=150, verbose_name='* city'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_marital_status', to='core.LookupModel', verbose_name='* Marital status'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_state', to='core.LookupModel', verbose_name='* State'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='street',
            field=models.CharField(max_length=50, verbose_name='* Address 1'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='zip_code',
            field=models.CharField(max_length=50, verbose_name='* Zip'),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='date_of_onset',
            field=models.CharField(max_length=50, verbose_name='Date Of Onset'),
        ),
    ]
