# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-03 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0003_auto_20190731_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemodel',
            name='names_covered_dependents',
            field=models.CharField(default='', max_length=550, verbose_name='Name(s) Of Covered Dependents'),
            preserve_default=False,
        ),
    ]
