# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0003_auto_20190811_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentinfomodel',
            name='diagnose_treated',
            field=models.ManyToManyField(blank=True, related_name='dep_diagnose_treated', to='core.LookupModel', verbose_name='Have you or any of your dependent(s) been diagnosed or treated for, or has hospitalization or surgery not yet performed been\n        recommended for, any of the following conditions in the past five (5) years? If so, the plan requires you to disclose these conditions solely\n        for underwriting purposes (and you can properly disclose by checking “Yes” for each of the conditions for which you and/or your\n        dependents have previously received diagnosis, treatment or a recommendation for hospitalization or surgery not yet performed).\n        Although neither you nor your dependents will be denied coverage because of any previous treatment, diagnosis or recommendation for\n        hospitalization or surgery not yet performed for any condition, if you fail to disclose any previous treatment, diagnosis, recommendation\n        of hospitalization or surgery not yet performed for a condition listed below, the health plan will not cover any medical expenses, diagnosis,\n        treatment, services, supplies, surgeries or hospitalizations for that undisclosed condition related or attributable, to the coverage sought\n        as part of this application. NOTE: You are required to disclose any updates to these health questions that may arise prior to the effective date of your coverage'),
        ),
    ]
