# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0004_auto_20190728_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragemodel',
            name='dependent_disabled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_dependent_disabled', to='core.LookupModel', verbose_name='Are you or any dependent(s) disabled?'),
        ),
    ]
