# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-04 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0004_coveragemodel_names_covered_dependents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='empl_full_name',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='empl_first_name',
            field=models.CharField(default='name', max_length=250, verbose_name='* First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='empl_last_name',
            field=models.CharField(default='name', max_length=250, verbose_name='* Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='address2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='empl_dob',
            field=models.DateTimeField(verbose_name='* DOB'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='empl_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_gender_lookupmodel', to='core.LookupModel', verbose_name='* Gender'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='empl_hire_date',
            field=models.DateTimeField(verbose_name='* Hire Date'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='empl_ssn',
            field=models.CharField(max_length=11, verbose_name='* SSN'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='hours_worked_per_week',
            field=models.IntegerField(verbose_name='* Working Status (30 hrs or more is Full Time)'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='job_title',
            field=models.CharField(default='job', max_length=150, verbose_name='* Job Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='zip_code',
            field=models.CharField(max_length=50, verbose_name='zip'),
        ),
    ]
