# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-04 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0005_auto_20190804_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='hours_worked_per_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_hours_wored', to='core.LookupModel', verbose_name='* Working Status (30 hrs or more is Full Time)'),
        ),
    ]
