# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0005_auto_20190811_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentinfomodel',
            name='anticipate_hozpital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_anticipate_hozpital', to='core.LookupModel', verbose_name='* Are you or any of your dependent(s) anticipating hospitalization or surgery, or had surgery or hospitalization\nrecommended that has not been performed? * If Yes, please provide information below'),
        ),
        migrations.AlterField(
            model_name='dependentinfomodel',
            name='dependent_pregnant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_dependent_pregnant', to='core.LookupModel', verbose_name='* Are you or any dependent(s) currently pregnant or suspect you / they may be pregnant? * If Yes, please provide due date and detail in space provided below'),
        ),
        migrations.AlterField(
            model_name='dependentinfomodel',
            name='past_24_med_cond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_past_24_med_cond', to='core.LookupModel', verbose_name='* Have you or any of your dependent(s) had any medical conditions in the past 24 months requiring medical care,\n        prescription management, surgery, or hospitalization? * If Yes, please provide information on who and for what conditions in space provided below'),
        ),
        migrations.AlterField(
            model_name='dependentinfomodel',
            name='past_24_mon_med_exp_5k',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_past_24_mon_med_exp_5k', to='core.LookupModel', verbose_name='* In the past 24 months, have you or any of your dependent(s) had more than $5,000 in medical expenses? * If Yes, please provide information on who and for what medical conditions in space provided below'),
        ),
        migrations.AlterField(
            model_name='dependentinfomodel',
            name='past_5_insu_decl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_past_5_ins_decl', to='core.LookupModel', verbose_name='* Within the past 5 years, have you or any dependent ever had an application for insurance declined, postponed,\n        rated or otherwise modified?'),
        ),
    ]
