# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0005_auto_20190728_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragemodel',
            name='tobacco_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tobacco_use', to='core.LookupModel', verbose_name='Tobacco Use'),
        ),
    ]
