# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-04 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_employer_employee'),
        ('healthquestionaire', '0006_auto_20190804_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='fk_employer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employerName', to='employer.Employer', verbose_name='Employer'),
            preserve_default=False,
        ),
    ]
