# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0006_auto_20190811_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='empl_dob',
            field=models.DateField(verbose_name='* DOB'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='empl_hire_date',
            field=models.DateField(verbose_name='* Hire Date'),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='date_last_seen',
            field=models.DateField(verbose_name='Date Last Seen By Physician'),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='date_of_onset',
            field=models.DateField(verbose_name='Date Of Onset'),
        ),
    ]
