# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0006_auto_20190728_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragemodel',
            name='coverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_coverage_accept', to='core.LookupModel', verbose_name='Accept/Decline'),
        ),
    ]
