# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0007_auto_20190811_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalmodel',
            name='date_last_seen',
            field=models.CharField(max_length=50, verbose_name='Date Last Seen By Physician'),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='date_of_onset',
            field=models.CharField(max_length=50, verbose_name='Date Of Onset'),
        ),
    ]
