# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-04 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0007_employeemodel_fk_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_state', to='core.LookupModel', verbose_name='State'),
        ),
    ]
