# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0007_auto_20190728_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragemodel',
            name='dependent_insurance_other_continue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_depend_other_insu_coverage', to='core.LookupModel', verbose_name='Do you, your spouse or your dependents have other health insurance coverage that will continue in addition to this coverage?'),
        ),
    ]
