# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-04 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0008_auto_20190804_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragemodel',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='coveragemodel',
            name='decline_reasons',
        ),
        migrations.RemoveField(
            model_name='coveragemodel',
            name='others',
        ),
        migrations.AlterField(
            model_name='coveragemodel',
            name='dependent_isu_coverage_carrier',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='If Yes, Name of Carrier'),
        ),
    ]
