# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0008_auto_20190728_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentinfomodel',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthquestionaire.EmployeeModel', verbose_name='For Employee'),
            preserve_default=False,
        ),
    ]
