# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-04 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190729_2047'),
        ('healthquestionaire', '0009_auto_20190804_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragemodel',
            name='coverage_level',
        ),
        migrations.AddField(
            model_name='coveragemodel',
            name='coverage_level',
            field=models.ForeignKey(default='22', on_delete=django.db.models.deletion.CASCADE, related_name='coverage_level', to='core.LookupModel', verbose_name='Coverage Level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coveragemodel',
            name='dependent_insurance_other_continue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_depend_other_insu_coverage', to='core.LookupModel', verbose_name='Do you or any of your family have other health insurance that will continue in addition to this coverage?'),
        ),
    ]
