# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-04 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0011_auto_20190804_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragemodel',
            name='names_covered_dependents',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='If Yes, Name(s) Of Covered Dependents'),
        ),
    ]
