# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-05 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190729_2047'),
        ('healthquestionaire', '0012_auto_20190804_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragemodel',
            name='decline_reasons',
            field=models.ManyToManyField(blank=True, related_name='reasons_for_decline', to='core.LookupModel', verbose_name='Reason for Decline'),
        ),
    ]
