# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-05 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0013_coveragemodel_decline_reasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragemodel',
            name='decline_reasons',
        ),
    ]
