# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-05 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='address2')),
                ('city', models.CharField(max_length=150, verbose_name='city')),
                ('state', models.CharField(max_length=200, verbose_name='state')),
                ('zip_code', models.CharField(max_length=50, verbose_name='zip_code')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('ssn', models.CharField(max_length=10, verbose_name='Social Security Number')),
                ('dob_dependent', models.DateTimeField(verbose_name='Date of Birth')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('tobacco_use', models.BooleanField(verbose_name='Tobacco Use')),
            ],
            options={
                'verbose_name': 'Dependent',
                'verbose_name_plural': 'Dependents',
                'db_table': 'employee_dependents',
            },
        ),
        migrations.CreateModel(
            name='HeightWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_feet', models.IntegerField(verbose_name='Feet')),
                ('height_inches', models.IntegerField(verbose_name='Inches')),
                ('weight_lbs', models.IntegerField(verbose_name='Weight in lbs')),
            ],
            options={
                'db_table': 'emp_height_weight',
            },
        ),
        migrations.CreateModel(
            name='LookupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_lookup', models.CharField(max_length=150, verbose_name='Key')),
                ('value_lookup', models.CharField(max_length=450, verbose_name='Value')),
                ('type_lookup', models.CharField(max_length=50, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Lookup',
                'verbose_name_plural': 'Lookup Data',
                'db_table': 'lookup_data',
            },
        ),
        migrations.CreateModel(
            name='MedicalConditionsTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.ManyToManyField(to='core.LookupModel', verbose_name='Conditions/Treatments')),
            ],
            options={
                'db_table': 'medical_conditions_treatments',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lookupmodel',
            unique_together=set([('key_lookup', 'type_lookup')]),
        ),
    ]
