# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('PHYSICAL', 'Physical Address'), ('MAIL', 'Mailing Address')], max_length=1)),
                ('street', models.CharField(blank=True, max_length=50, verbose_name='street')),
                ('address2', models.CharField(blank=True, max_length=150, verbose_name='address2')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=200, verbose_name='state')),
                ('zip_code', models.CharField(blank=True, max_length=50, verbose_name='zip_code')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'verbose_name': 'Address',
            },
        ),
    ]
