# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.LookupModel', verbose_name='Address Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedependent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthquestionaire.EmployeeModel', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeedependent',
            name='gender',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, related_name='empl_gender', to='core.LookupModel', verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedependent',
            name='relationship',
            field=models.ForeignKey(default=95, on_delete=django.db.models.deletion.CASCADE, related_name='empl_relationship', to='core.LookupModel', verbose_name='Relationship to Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeedependent',
            name='tobacco_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tobacco_use', to='core.LookupModel', verbose_name='Tobacco Use'),
        ),
    ]
