# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-05 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190729_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedependent',
            name='tobacco_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tobacco_use', to='core.LookupModel', verbose_name='Tobacco Use'),
        ),
    ]
