# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-11 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190805_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedependent',
            name='ssn',
            field=models.CharField(max_length=11, verbose_name='Social Security Number'),
        ),
    ]
