# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-15 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('relationship', models.CharField(choices=[('SPOUSE', 'SPOUSE'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER')], max_length=10, verbose_name='Relationship to Employee')),
                ('ssn', models.CharField(max_length=10, verbose_name='Social Security Number')),
                ('dob_dependent', models.DateTimeField(verbose_name='Date of Birth')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('tobacco_use', models.BooleanField(verbose_name='Tobacco Use')),
                ('coverage', models.CharField(choices=[('DECLINE', 'I Decline Coverage'), ('ACCEPT', 'I Accept Coverage')], max_length=50, verbose_name='coverage')),
                ('decline_reasons', models.CharField(choices=[('SP_EMP_PLAN', "SPOUSE'S EMPLOYER'S PLAN"), ('IND_PLAN', 'INDIVIDUAL PLAN'), ('MEDICARE', 'MEDICARE'), ('MEDICAID', 'MEDICAID'), ('COBRA_PREV_EMP', 'COBRA FROM PREVIOUS EMPLOYER'), ('VA_ELIG', 'VA ELIGIBILITY'), ('NO_COVERAGE_NOW', 'I HAVE NO COVERAGE AT THIS TIME'), ('OTHERS', 'OTHERS')], max_length=50, verbose_name='Reason for Decline')),
                ('others', models.CharField(max_length=150, verbose_name='Others')),
            ],
            options={
                'verbose_name_plural': 'Dependents',
                'db_table': 'employee_dependents',
                'verbose_name': 'Dependent',
            },
        ),
        migrations.CreateModel(
            name='HeightWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_feet', models.IntegerField(verbose_name='Feet')),
                ('height_inches', models.IntegerField(verbose_name='Inches')),
                ('weight_lbs', models.IntegerField(verbose_name='Weight in lbs')),
            ],
            options={
                'db_table': 'emp_height_weight',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Address'), ('MAIL', 'Mailing Address')], max_length=10),
        ),
        migrations.AddField(
            model_name='employeedependent',
            name='self_height_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_height_weight', to='core.HeightWeight', verbose_name='Self'),
        ),
        migrations.AddField(
            model_name='employeedependent',
            name='spouse_height_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_height_weight', to='core.HeightWeight', verbose_name='Spouse'),
        ),
    ]
