# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190811_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedependent',
            name='dob_dependent',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
