# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190715_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalConditionsTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.CharField(choices=[('CARDIAC_DISORDER', 'Cardiac Disorder'), ('CANCER_TUMOR_ANY_FORM', 'Cancer Tumor (any form)'), ('DIABETES', 'Diabetes'), ('KIDNEY_DISORDER', 'Kidney Disorder')], max_length=50, verbose_name='Conditions/Treatments')),
            ],
            options={
                'db_table': 'medical_conditions_treatments',
            },
        ),
    ]
