# Generated by Django 2.1.5 on 2019-08-23 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('core', '0004_auto_20190811_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employer.Employer', verbose_name='Employer'),
            preserve_default=False,
        ),
    ]
