# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-15 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicalconditionstreatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedependent',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='employeedependent',
            name='decline_reasons',
        ),
        migrations.RemoveField(
            model_name='employeedependent',
            name='others',
        ),
        migrations.RemoveField(
            model_name='employeedependent',
            name='self_height_weight',
        ),
        migrations.RemoveField(
            model_name='employeedependent',
            name='spouse_height_weight',
        ),
    ]
