# Generated by Django 2.1.5 on 2019-08-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.Employer', verbose_name='Employer'),
        ),
    ]
