# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 01:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import form_application.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20190729_2047'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthquestionaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=form_application.models.upload_location, verbose_name='Application Form')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthquestionaire.EmployeeModel', verbose_name='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LookupModel', verbose_name='Forms')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'db_table': 'pdf_forms_submitted',
            },
        ),
    ]
