# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PdfModel',
            new_name='ApplicationModel',
        ),
    ]
