# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Employer Name')),
                ('ein', models.CharField(blank=True, max_length=150, null=True, verbose_name='EIN')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='address2')),
                ('city', models.CharField(max_length=150, verbose_name='city')),
                ('state', models.CharField(max_length=200, verbose_name='state')),
                ('zip_code', models.CharField(max_length=50, verbose_name='zip_code')),
            ],
            options={
                'db_table': 'employers',
            },
        ),
    ]
