# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('employer_address', models.ForeignKey(db_column='employer_address', on_delete=django.db.models.deletion.CASCADE, related_name='employer_address', to='core.Address', verbose_name='EmployerAddress')),
            ],
            options={
                'db_table': 'employers',
            },
        ),
    ]
