# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthquestionaire', '0003_auto_20190731_2136'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employee',
            field=models.ManyToManyField(to='healthquestionaire.EmployeeModel', verbose_name=''),
        ),
    ]
