# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_employer_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employee',
            field=models.ManyToManyField(to='healthquestionaire.EmployeeModel', verbose_name='Employee Employer Relation'),
        ),
    ]
