# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-04 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_employer_employee'),
        ('employer', '0004_remove_employer_ein'),
    ]

    operations = [
    ]
